### ISSUE TITLE
请问有RxJava2版本么

### ISSUE THREAD

**Issue by sweet2o09** [LiqiNew/NoHttpRxUtils#1]

**Comment by LiqiNew** [comment]
暂时还没有支持上去。是不是你的项目已经依赖与rxjava2了？

**Comment by sweet2o09** [comment]
是的,目前使用的是retrofit2+rxjava2然后用rxlifecycle2管理生命周期

**Comment by LiqiNew** [comment]
既然你已经用上了retrofit2+rxjava2。你是打算换一个网络请求框架吗？

**Comment by sweet2o09** [comment]
你好,是这样的,我现在用的是我自己封装的网络请求框架,感觉不是很理想,之前在NoHttp那边看到推荐了你的这个框架,感觉封装的比较好,所以想搬运过来用用,顺便学习下

**Comment by LiqiNew** [comment]
那我想办法把Rxjava版本升上去。我先去看看rxjava2比rxjava1变动了那些，增加了那些特性。然后去针对rxjava2升级。

**Comment by sweet2o09** [comment]
哈哈,好的,谢谢

**Comment by LiqiNew** [comment]
你的rxjava2版本只是用在跟retrofit2捆绑吗？如果你只是用在retrofit2哪里，那么你换网络请求的时候，可以把rxjava2移除掉。这样就不会产生冲突了。

**Comment by sweet2o09** [comment]
不是的,RxJava2我项目中也有用到,还是挺好用的

**Comment by LiqiNew** [comment]
恩，那我有时间想办法去兼容到rxjava2。先让我把rxjava摸熟先。要不怕坑了别人。

**Comment by sweet2o09** [comment]
http://www.jianshu.com/p/464fa025229e
http://www.jianshu.com/p/a93c79e9f689
http://www.jianshu.com/p/6d644ca1678f
我当时是通过这三篇文章熟悉Rxjava2的

**Comment by LiqiNew** [comment]
恩。谢谢啦。

**Comment by LiqiNew** [comment]
OK,现在支持rxjava2。非常感谢你的提议
