### ISSUE TITLE
轮询请求第二次请求body参数不传值

### ISSUE THREAD

**Issue by LikCodeLab** [LiqiNew/NoHttpRxUtils#11]
轮询请求同一个接口，第一次请求加入了body请求参数获取数据成功，第二次就不传请求参数，然后一直请求错误
![image](https://user-images.githubusercontent.com/15062292/53312997-62107e80-38f2-11e9-84d4-ac854b800799.png)

**Comment by LikCodeLab** [comment]
这是轮询第一次
![image](https://user-images.githubusercontent.com/15062292/53314707-bae41500-38fa-11e9-9209-cee319a4f113.png)

**Comment by LikCodeLab** [comment]
这是轮询的第二次
![image](https://user-images.githubusercontent.com/15062292/53314904-b66c2c00-38fb-11e9-9ebb-62d7cba1305d.png)

**Comment by LiqiNew** [comment]
轮询第二次的时候。body已经被nohttp框架内部销毁了。所有用body形式去轮询是不行的

**Comment by Weidoudi** [comment]
想使用body没有解决方案？

**Comment by LiqiNew** [comment]
因为nohttp底层实现问题。如果第二次请求的话是不行的。




------------------ 原始邮件 ------------------
发件人: "Weidoudi"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 下午2:21
收件人: "LiqiNew/NoHttpRxUtils"<NoHttpRxUtils@noreply.github.com>;
抄送: "棋子"<543945827@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [LiqiNew/NoHttpRxUtils] 轮询请求第二次请求body参数不传值 (#11)




想使用body没有解决方案？
