### ISSUE TITLE
上传进度条问题

### ISSUE THREAD

**Issue by lwl49** [LiqiNew/NoHttpRxUtils#12]
你好，请问这个工具有上传进度条么？文件上传如何进行啊

**Comment by LiqiNew** [comment]
请参考demo上的文件上传案例。

------------------
Best Regards


IT/李奇
博客：https://github.com/LiqiNew


 




------------------ 原始邮件 ------------------
发件人: "lwl49"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 晚上6:22
收件人: "LiqiNew/NoHttpRxUtils"<NoHttpRxUtils@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [LiqiNew/NoHttpRxUtils] 上传进度条问题 (#12)




你好，请问这个工具有上传进度条么？文件上传如何进行啊
