### ISSUE TITLE
统一格式问题

### ISSUE THREAD

**Issue by KotlinLan** [LiqiNew/NoHttpRxUtils#13]
public class BaseResponse<T> implements Serializable {

    private int code;
    private T data;
    private String msg;

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
}

请问这种怎么封装。谢谢！

**Comment by LiqiNew** [comment]
通过子类继承这个父类，然后把子类的.calss传给框架去自动解析。

**Comment by LiqiNew** [comment]
通过子类继承这个父类，然后把子类的.calss传给框架去自动解析。
