### ISSUE TITLE
怎么获取后台返回的header

### ISSUE THREAD

**Issue by dongdianyi** [LiqiNew/NoHttpRxUtils#15]

**Comment by LiqiNew** [comment]
请看获取数据的源代码。


Best Regards


IT/李奇
博客：https://github.com/LiqiNew


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dongdianyi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 晚上7:30
收件人:&nbsp;"LiqiNew/NoHttpRxUtils"<NoHttpRxUtils@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LiqiNew/NoHttpRxUtils] 怎么获取后台返回的header (#15)
