### ISSUE TITLE
求教，同一个界面使用多个接口，怎么拿到这些数据？

### ISSUE THREAD

**Issue by wjy591416** [LiqiNew/NoHttpRxUtils#3]
看过你的dome，一个界面中仅仅访问了一个接口，那么在onNext中确实不用区分获取数据，但是我在实际应用中，很多情况都是多次调用接口，我看到有setSign（object）这个函数，请问，怎么获取对应setSign的接口中数据？

**Comment by LiqiNew** [comment]
你如果不是使用MVP架构去请求的话，那么就直接在你调用请求接口的时候，直接匿名内部类去new那个回调接口。如果你使用MVP架构去请求的话。那么就用自定义类型对象去处理对应的网络请求。你在自定义对象定一个变量type，比如网络1请求，那么type=1，如果是网络请求2，那么type=2.以此类推，这个是你自己去定义的。框架不处理这个问题。
