### ISSUE TITLE
下载文件命名问题

### ISSUE THREAD

**Issue by MrsLi** [LiqiNew/NoHttpRxUtils#5]
使用框架下载的文件都是以.nohttp结尾的,是什么情况?
比如我要下载的文件命名为  A.mp4,下载后就变成了  A.mp4.nohttp

**Comment by LiqiNew** [comment]
不会呀。下载完毕的文件都是以你指定的文件为准啊。
 .addDownloadParameter(下载文件url, "指定的文件名记得带扩展名")

**Comment by LiqiNew** [comment]
已修复
