### ISSUE TITLE
如何实现多任务下载？

### ISSUE THREAD

**Issue by MrsLi** [LiqiNew/NoHttpRxUtils#6]
项目中用的视频下载，多个视频同时下载有问题，下载第二个的时候会覆盖第一个的下载任务

**Comment by MrsLi** [comment]
多任务下载的时候怎么区分是返回的下载进度是属于哪个下载的？

**Comment by MrsLi** [comment]
拿个what值什么？

**Comment by LiqiNew** [comment]
新年快乐。由于是春节期间，老家没有网络。所有没有看到不好意思啊。多任务下载一定要保证的下载名称唯一才不会覆盖。

**Comment by MrsLi** [comment]
没关系，想请教一下，多任务下载的时候怎么区分是返回的下载进度是属于哪个下载的？

**Comment by LiqiNew** [comment]
你可以参考demo里面的多任务下载。哪里有完整的演示。

**Comment by MrsLi** [comment]
跟我写的那个不太一样，刚开始没看明白demo，现在问题解决了，非常谢谢！
