### ISSUE TITLE
下载退出后重新下载的问题

### ISSUE THREAD

**Issue by MrsLi** [LiqiNew/NoHttpRxUtils#7]
我下载视频文件，暂停后，退出程序，再次进入程序的时候不能够使用NohttpDownloadUtils.startRequest(downloadUrl);来恢复该条下载任务吗？

**Comment by LiqiNew** [comment]
你是退出程序还是把程序放到后台不可见？

**Comment by MrsLi** [comment]
是退出程序，然后清理后台运行的

**Comment by MrsLi** [comment]
程序放到后台一切都是正常的，就是程序退出并清理内存后，NohttpDownloadUtils.startRequest(downloadUrl);
NohttpDownloadUtils.startAllRequest();这两个方法都没办法使用了，我需要怎么做？急！！！

**Comment by LiqiNew** [comment]
你在退出界面结束的生命周期方法里面调用下载关闭方法试试看看。
