### ISSUE TITLE
下载了个html文件，里面带有图片失真不能展示

### ISSUE THREAD

**Issue by wangjjj** [LiqiNew/NoHttpRxUtils#8]
下载链接如https://www.huishangsuo.com/pad/Commoninfo/creditinfo?uid=159&uniquestr=sgB%2FuhsGCD5VY8gb1AVXGQMKx8eqGpe133MFZ6i9WNEM5QGQTww&id=slB4vxwAU2hWYshr&type=3 
里面含的图片地址如https://hssbj01.oss-cn-beijing.aliyuncs.com//Pad/sign/201806/1529380281691JPEG_20180619_114428.jpg?x-oss-process=image/resize,h_210
下载下来后图片无效，做了证书认证还是不行，不知道怎么办了，求指教

**Comment by LiqiNew** [comment]
你的下载链接里面网址有隐私的内容。另外你试试https://hssbj01.oss-cn-beijing.aliyuncs.com//Pad/sign/201806/1529380281691JPEG_20180619_114428.jpg?x-oss-process=image/resize,h_210变成https://hssbj01.oss-cn-beijing.aliyuncs.com//Pad/sign/201806/1529380281691JPEG_20180619_114428.jpg试试。?切割取前面的内容下载。
